default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: Auto update by pre-commit hooks [skip changelog]"
  autofix_prs: true
repos:
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.2
    hooks:
      - id: oxipng
        files: \\.png$
        types: [file]
        args: ["-q", "-o", "2", "-s", "--ng"]
  - repo: local
    # 使用 local 定义 Prettier，避免 mirrors-prettier 仓库已归档且缺少稳定 v3 标签的问题
    hooks:
      - id: prettier
        name: prettier (yaml+json)
        entry: prettier
        language: node
        # 仅格式化 YAML / JSON，可按需扩展 (e.g. add markdown, javascript)
        types_or: [yaml, json]
        pass_filenames: true
        additional_dependencies:
          - prettier@3.3.3
          - prettier-plugin-multiline-arrays@^3.0.0
        # 如出现 Windows file:// 路径问题，可暂时移除插件或添加 .prettierrc.json 手动指定 plugins
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        files: ^docs/.*|^README\.md$
        types:
          - markdown
        args: ["--fix", "--config", "docs/.markdownlint.yaml", "#**/node_modules"]
